[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wsol = "wso1PkvZVRh2KSdrhBeFFd15E36ggcwuwp8qmdqDVjn"
[programs.devnet]
wsol = "wso1PkvZVRh2KSdrhBeFFd15E36ggcwuwp8qmdqDVjn"

[registry]
url = "https://api.apr.dev"

[provider]
# localnet devnet
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[test]
startup_wait = 10000
